In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

# Series

In [6]:
s1 = pd.Series(['a', 'b', 'c', 'd', 'e'])
s1

0    a
1    b
2    c
3    d
4    e
dtype: object

In [7]:
s2 = pd.Series(['a', 'b', 'c', 'd', 'e'], index = [10, 20, 30, 40, 50])
s2

10    a
20    b
30    c
40    d
50    e
dtype: object

In [8]:
s2[20]

'b'

In [9]:
d1 = {'a':1, 'b':2, 'c':3}
d1

{'a': 1, 'b': 2, 'c': 3}

In [10]:
s3 = pd.Series(d1)
s3

a    1
b    2
c    3
dtype: int64

In [11]:
s4 = pd.Series(d1, index = ['e', 'a', 'g', 'b'])
s4

e    NaN
a    1.0
g    NaN
b    2.0
dtype: float64

In [12]:
s5 = pd.Series({'a':1, 'b':2, 'c':3, 'd':4})
s5

a    1
b    2
c    3
d    4
dtype: int64

In [13]:
s5['c']

3

In [14]:
s5[2]

3

# Dataframe

In [29]:
d1 = {'Name' : ['Ch Ayushman Patro', 'Anushka Palo', 'Ashok Swain', 'Lipsa Rani Gouda', 'Ayush Pattnaik'],
      'Course' : ['Data Science', 'Data Analytics', 'Archeology', 'Data Analytics', 'Android Development'],
      'Marks' : [71, 98, 96, 97, 90]}
d1

{'Name': ['Ch Ayushman Patro',
  'Anushka Palo',
  'Ashok Swain',
  'Lipsa Rani Gouda',
  'Ayush Pattnaik'],
 'Course': ['Data Science',
  'Data Analytics',
  'Archeology',
  'Data Analytics',
  'Android Development'],
 'Marks': [71, 98, 96, 97, 90]}

In [30]:
df1 = pd.DataFrame(d1)
df1

                Name               Course  Marks
0  Ch Ayushman Patro         Data Science     71
1       Anushka Palo       Data Analytics     98
2        Ashok Swain           Archeology     96
3   Lipsa Rani Gouda       Data Analytics     97
4     Ayush Pattnaik  Android Development     90

In [31]:
df1.head(2)

                Name          Course  Marks
0  Ch Ayushman Patro    Data Science     71
1       Anushka Palo  Data Analytics     98

In [32]:
df1.tail(2)

               Name               Course  Marks
3  Lipsa Rani Gouda       Data Analytics     97
4    Ayush Pattnaik  Android Development     90

In [34]:
df1.rename(columns = {'Name' : 'Student Name'}, inplace = True)
df1

        Student Name               Course  Marks
0  Ch Ayushman Patro         Data Science     71
1       Anushka Palo       Data Analytics     98
2        Ashok Swain           Archeology     96
3   Lipsa Rani Gouda       Data Analytics     97
4     Ayush Pattnaik  Android Development     90

In [35]:
df1.set_index('Student Name', inplace = True)
df1

                                Course  Marks
Student Name
Ch Ayushman Patro         Data Science     71
Anushka Palo            Data Analytics     98
Ashok Swain                 Archeology     96
Lipsa Rani Gouda        Data Analytics     97
Ayush Pattnaik     Android Development     90