In [1]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({'Days' : [1, 2, 3, 4, 5],
                    'Places' : ['Puri', 'Bali', np.NaN, 'Dehli', np.NaN],
                    'Visitors' : [5800, 4500, 5000, 3000, 2000]})
df1

   Days Places  Visitors
0     1   Puri      5800
1     2   Bali      4500
2     3    NaN      5000
3     4  Dehli      3000
4     5    NaN      2000

In [4]:
df1.dtypes #Returns the datatype of the values available in particular columns

Days         int64
Places      object
Visitors     int64
dtype: object

In [5]:
df1.info() #Returns all information regarding the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Days      5 non-null      int64
 1   Places    3 non-null      object
 2   Visitors  5 non-null      int64
dtypes: int64(2), object(1)
memory usage: 252.0+ bytes

# Handling Missing Values

In [6]:
df1.isnull() # isnull() returns True and False accordingly where NaN values are available or not

    Days  Places  Visitors
0  False   False     False
1  False   False     False
2  False    True     False
3  False   False     False
4  False    True     False

In [7]:
df1.isnull().sum() # isnull().sum() returns the count of NaN values of all columns available in the dataframe

Days        0
Places      2
Visitors    0
dtype: int64

**< df >.< column >.fillna(< new_value >, inplace = True)**

In [8]:
df1.Places.fillna('Puri', inplace = True)
df1

   Days Places  Visitors
0     1   Puri      5800
1     2   Bali      4500
2     3   Puri      5000
3     4  Dehli      3000
4     5   Puri      2000

In [9]:
df1.isnull().sum()

Days        0
Places      0
Visitors    0
dtype: int64

**< df >.< column >.unique()** -> Returns unique values of that particular column

# Statistical Functions

In [10]:
df1.Places.unique()

array(['Puri', 'Bali', 'Dehli'], dtype=object)

In [11]:
df1['Places'].unique()

array(['Puri', 'Bali', 'Dehli'], dtype=object)

In [12]:
df1.Visitors.mean()

4060.0

In [13]:
df1['Visitors'].mean()

4060.0

In [14]:
df1.Visitors.median()

4500.0

In [15]:
df1['Visitors'].median()

4500.0

In [16]:
df1.Places.mode()

0    Puri
Name: Places, dtype: object

In [17]:
df1['Places'].mode()

0    Puri
Name: Places, dtype: object

In [18]:
df1.Visitors.max()

5800

In [19]:
df1['Visitors'].max()

5800

In [20]:
df1.Visitors.min()

2000

In [21]:
df1['Visitors'].min()

2000

In [22]:
df1.Visitors.var()

2368000.0

In [23]:
df1['Visitors'].var()

2368000.0

In [24]:
df1.Visitors.std()

1538.8307249337076

In [25]:
df1['Visitors'].std()

1538.8307249337076

In [26]:
df1.describe()

           Days     Visitors
count  5.000000     5.000000
mean   3.000000  4060.000000
std    1.581139  1538.830725
min    1.000000  2000.000000
25%    2.000000  3000.000000
50%    3.000000  4500.000000
75%    4.000000  5000.000000
max    5.000000  5800.000000

In [27]:
df1.describe(include = "all")

            Days Places     Visitors
count   5.000000      5     5.000000
unique       NaN      3          NaN
top          NaN   Puri          NaN
freq         NaN      3          NaN
mean    3.000000    NaN  4060.000000
std     1.581139    NaN  1538.830725
min     1.000000    NaN  2000.000000
25%     2.000000    NaN  3000.000000
50%     3.000000    NaN  4500.000000
75%     4.000000    NaN  5000.000000
max     5.000000    NaN  5800.000000

In [28]:
df1.describe(include = 'O')

       Places
count       5
unique      3
top      Puri
freq        3

# Iris Data Analysis

In [29]:
idf = pd.read_csv(".\Datasets\Iris-Dataset\iris.data", header = None)
idf

       0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [30]:
idf.columns = ['SL', 'SW', 'PL', 'PW', 'CLASS']
idf

      SL   SW   PL   PW           CLASS
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [31]:
idf.head(3)

    SL   SW   PL   PW        CLASS
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa

In [32]:
idf.tail(2)

      SL   SW   PL   PW           CLASS
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

In [33]:
idf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   SL      150 non-null    float64
 1   SW      150 non-null    float64
 2   PL      150 non-null    float64
 3   PW      150 non-null    float64
 4   CLASS   150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [34]:
idf.isnull()

        SL     SW     PL     PW  CLASS
0    False  False  False  False  False
1    False  False  False  False  False
2    False  False  False  False  False
3    False  False  False  False  False
4    False  False  False  False  False
..     ...    ...    ...    ...    ...
145  False  False  False  False  False
146  False  False  False  False  False
147  False  False  False  False  False
148  False  False  False  False  False
149  False  False  False  False  False

[150 rows x 5 columns]

In [35]:
idf.isnull().sum()

SL       0
SW       0
PL       0
PW       0
CLASS    0
dtype: int64

In [36]:
idf.CLASS.unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [37]:
for i in idf.columns: print(i,':\n',idf[i].unique())

SL :
 [5.1 4.9 4.7 4.6 5.  5.4 4.4 4.8 4.3 5.8 5.7 5.2 5.5 4.5 5.3 7.  6.4 6.9
 6.5 6.3 6.6 5.9 6.  6.1 5.6 6.7 6.2 6.8 7.1 7.6 7.3 7.2 7.7 7.4 7.9]
SW :
 [3.5 3.  3.2 3.1 3.6 3.9 3.4 2.9 3.7 4.  4.4 3.8 3.3 4.1 4.2 2.3 2.8 2.4
 2.7 2.  2.2 2.5 2.6]
PL :
 [1.4 1.3 1.5 1.7 1.6 1.1 1.2 1.  1.9 4.7 4.5 4.9 4.  4.6 3.3 3.9 3.5 4.2
 3.6 4.4 4.1 4.8 4.3 5.  3.8 3.7 5.1 3.  6.  5.9 5.6 5.8 6.6 6.3 6.1 5.3
 5.5 6.7 6.9 5.7 6.4 5.4 5.2]
PW :
 [0.2 0.4 0.3 0.1 0.5 0.6 1.4 1.5 1.3 1.6 1.  1.1 1.8 1.2 1.7 2.5 1.9 2.1
 2.2 2.  2.4 2.3]
CLASS :
 ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']

In [38]:
idf.describe()

               SL          SW          PL          PW
count  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.054000    3.758667    1.198667
std      0.828066    0.433594    1.764420    0.763161
min      4.300000    2.000000    1.000000    0.100000
25%      5.100000    2.800000    1.600000    0.300000
50%      5.800000    3.000000    4.350000    1.300000
75%      6.400000    3.300000    5.100000    1.800000
max      7.900000    4.400000    6.900000    2.500000

In [39]:
idf.describe(include = 'O')

              CLASS
count           150
unique            3
top     Iris-setosa
freq             50

In [40]:
idf.describe(include = "all")

                SL          SW          PL          PW        CLASS
count   150.000000  150.000000  150.000000  150.000000          150
unique         NaN         NaN         NaN         NaN            3
top            NaN         NaN         NaN         NaN  Iris-setosa
freq           NaN         NaN         NaN         NaN           50
mean      5.843333    3.054000    3.758667    1.198667          NaN
std       0.828066    0.433594    1.764420    0.763161          NaN
min       4.300000    2.000000    1.000000    0.100000          NaN
25%       5.100000    2.800000    1.600000    0.300000          NaN
50%       5.800000    3.000000    4.350000    1.300000          NaN
75%       6.400000    3.300000    5.100000    1.800000          NaN
max       7.900000    4.400000    6.900000    2.500000          NaN

In [41]:
idf["CLASS"].value_counts()

CLASS
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [42]:
for i in idf.columns: print(idf[i].value_counts())

SL
5.0    10
5.1     9
6.3     9
5.7     8
6.7     8
5.8     7
5.5     7
6.4     7
4.9     6
5.4     6
6.1     6
6.0     6
5.6     6
4.8     5
6.5     5
6.2     4
7.7     4
6.9     4
4.6     4
5.2     4
5.9     3
4.4     3
7.2     3
6.8     3
6.6     2
4.7     2
7.6     1
7.4     1
7.3     1
7.0     1
7.1     1
5.3     1
4.3     1
4.5     1
7.9     1
Name: count, dtype: int64
SW
3.0    26
2.8    14
3.2    13
3.1    12
3.4    12
2.9    10
2.7     9
2.5     8
3.5     6
3.3     6
3.8     6
2.6     5
2.3     4
3.7     3
2.4     3
2.2     3
3.6     3
3.9     2
4.4     1
4.0     1
4.1     1
4.2     1
2.0     1
Name: count, dtype: int64
PL
1.5    14
1.4    12
5.1     8
4.5     8
1.6     7
1.3     7
5.6     6
4.7     5
4.9     5
4.0     5
4.2     4
5.0     4
4.4     4
4.8     4
1.7     4
3.9     3
4.6     3
5.7     3
4.1     3
5.5     3
6.1     3
5.8     3
3.3     2
5.4     2
6.7     2
5.3     2
5.9     2
6.0     2
1.2     2
4.3     2
1.9     2
3.5     2
5.2     2
3.0     1
1.1     1
3.7     1
3.8     1
6.6     1
6.3     1
1.0     1
6.9     1
3.6     1
6.4     1
Name: count, dtype: int64
PW
0.2    28
1.3    13
1.8    12
1.5    12
1.4     8
2.3     8
1.0     7
0.4     7
0.3     7
0.1     6
2.1     6
2.0     6
1.2     5
1.9     5
1.6     4
2.5     3
2.2     3
2.4     3
1.1     3
1.7     2
0.6     1
0.5     1
Name: count, dtype: int64
CLASS
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

# Auto MPG Data Analysis

In [43]:
adf = pd.read_csv(r".\Datasets\Auto-MPG-Dataset\auto-mpg.data", delim_whitespace = True, header = None)
adf

        0  1      2      3       4     5   6  7                          8
0    18.0  8  307.0  130.0  3504.0  12.0  70  1  chevrolet chevelle malibu
1    15.0  8  350.0  165.0  3693.0  11.5  70  1          buick skylark 320
2    18.0  8  318.0  150.0  3436.0  11.0  70  1         plymouth satellite
3    16.0  8  304.0  150.0  3433.0  12.0  70  1              amc rebel sst
4    17.0  8  302.0  140.0  3449.0  10.5  70  1                ford torino
..    ... ..    ...    ...     ...   ...  .. ..                        ...
393  27.0  4  140.0  86.00  2790.0  15.6  82  1            ford mustang gl
394  44.0  4   97.0  52.00  2130.0  24.6  82  2                  vw pickup
395  32.0  4  135.0  84.00  2295.0  11.6  82  1              dodge rampage
396  28.0  4  120.0  79.00  2625.0  18.6  82  1                ford ranger
397  31.0  4  119.0  82.00  2720.0  19.4  82  1                 chevy s-10

[398 rows x 9 columns]

In [44]:
adf.columns = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin', 'car_name']
adf

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150.0,3433.0,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140.0,3449.0,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86.00,2790.0,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52.00,2130.0,24.6,82,2,vw pickup
395,32.0,4,135.0,84.00,2295.0,11.6,82,1,dodge rampage
396,28.0,4,120.0,79.00,2625.0,18.6,82,1,ford ranger
397,31.0,4,119.0,82.00,2720.0,19.4,82,1,chevy s-10

In [45]:
adf.isnull()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,car_name
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
393,False,False,False,False,False,False,False,False,False
394,False,False,False,False,False,False,False,False,False
395,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False

In [46]:
adf.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
car_name        0
dtype: int64

In [47]:
adf.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

In [48]:
for i in adf.columns: print(i,":\n",adf[i].unique())

mpg :
 [18.  15.  16.  17.  14.  24.  22.  21.  27.  26.  25.  10.  11.   9.
 28.  19.  12.  13.  23.  30.  31.  35.  20.  29.  32.  33.  17.5 15.5
 14.5 22.5 24.5 18.5 29.5 26.5 16.5 31.5 36.  25.5 33.5 20.5 30.5 21.5
 43.1 36.1 32.8 39.4 19.9 19.4 20.2 19.2 25.1 20.6 20.8 18.6 18.1 17.7
 27.5 27.2 30.9 21.1 23.2 23.8 23.9 20.3 21.6 16.2 19.8 22.3 17.6 18.2
 16.9 31.9 34.1 35.7 27.4 25.4 34.2 34.5 31.8 37.3 28.4 28.8 26.8 41.5
 38.1 32.1 37.2 26.4 24.3 19.1 34.3 29.8 31.3 37.  32.2 46.6 27.9 40.8
 44.3 43.4 36.4 44.6 40.9 33.8 32.7 23.7 23.6 32.4 26.6 25.8 23.5 39.1
 39.  35.1 32.3 37.7 34.7 34.4 29.9 33.7 32.9 31.6 28.1 30.7 24.2 22.4
 34.  38.  44. ]
cylinders :
 [8 4 6 3 5]
displacement :
 [307.  350.  318.  304.  302.  429.  454.  440.  455.  390.  383.  340.
 400.  113.  198.  199.  200.   97.  110.  107.  104.  121.  360.  140.
  98.  232.  225.  250.  351.  258.  122.  116.   79.   88.   71.   72.
  91.   97.5  70.  120.   96.  108.  155.   68.  114.  156.   76.   83.
  90.  231.  262.  134.  119.  171.  115.  101.  305.   85.  130.  168.
 111.  260.  151.  146.   80.   78.  105.  131.  163.   89.  267.   86.
 183.  141.  173.  135.   81.  100.  145.  112.  181.  144. ]
horsepower :
 ['130.0' '165.0' '150.0' '140.0' '198.0' '220.0' '215.0' '225.0' '190.0'
 '170.0' '160.0' '95.00' '97.00' '85.00' '88.00' '46.00' '87.00' '90.00'
 '113.0' '200.0' '210.0' '193.0' '?' '100.0' '105.0' '175.0' '153.0'
 '180.0' '110.0' '72.00' '86.00' '70.00' '76.00' '65.00' '69.00' '60.00'
 '80.00' '54.00' '208.0' '155.0' '112.0' '92.00' '145.0' '137.0' '158.0'
 '167.0' '94.00' '107.0' '230.0' '49.00' '75.00' '91.00' '122.0' '67.00'
 '83.00' '78.00' '52.00' '61.00' '93.00' '148.0' '129.0' '96.00' '71.00'
 '98.00' '115.0' '53.00' '81.00' '79.00' '120.0' '152.0' '102.0' '108.0'
 '68.00' '58.00' '149.0' '89.00' '63.00' '48.00' '66.00' '139.0' '103.0'
 '125.0' '133.0' '138.0' '135.0' '142.0' '77.00' '62.00' '132.0' '84.00'
 '64.00' '74.00' '116.0' '82.00']
weight :
 [3504. 3693. 3436. 3433. 3449. 4341. 4354. 4312. 4425. 3850. 3563. 3609.
 3761. 3086. 2372. 2833. 2774. 2587. 2130. 1835. 2672. 2430. 2375. 2234.
 2648. 4615. 4376. 4382. 4732. 2264. 2228. 2046. 2634. 3439. 3329. 3302.
 3288. 4209. 4464. 4154. 4096. 4955. 4746. 5140. 2962. 2408. 3282. 3139.
 2220. 2123. 2074. 2065. 1773. 1613. 1834. 1955. 2278. 2126. 2254. 2226.
 4274. 4385. 4135. 4129. 3672. 4633. 4502. 4456. 4422. 2330. 3892. 4098.
 4294. 4077. 2933. 2511. 2979. 2189. 2395. 2288. 2506. 2164. 2100. 4100.
 3988. 4042. 3777. 4952. 4363. 4237. 4735. 4951. 3821. 3121. 3278. 2945.
 3021. 2904. 1950. 4997. 4906. 4654. 4499. 2789. 2279. 2401. 2379. 2124.
 2310. 2472. 2265. 4082. 4278. 1867. 2158. 2582. 2868. 3399. 2660. 2807.
 3664. 3102. 2875. 2901. 3336. 2451. 1836. 2542. 3781. 3632. 3613. 4141.
 4699. 4457. 4638. 4257. 2219. 1963. 2300. 1649. 2003. 2125. 2108. 2246.
 2489. 2391. 2000. 3264. 3459. 3432. 3158. 4668. 4440. 4498. 4657. 3907.
 3897. 3730. 3785. 3039. 3221. 3169. 2171. 2639. 2914. 2592. 2702. 2223.
 2545. 2984. 1937. 3211. 2694. 2957. 2671. 1795. 2464. 2572. 2255. 2202.
 4215. 4190. 3962. 3233. 3353. 3012. 3085. 2035. 3651. 3574. 3645. 3193.
 1825. 1990. 2155. 2565. 3150. 3940. 3270. 2930. 3820. 4380. 4055. 3870.
 3755. 2045. 1945. 3880. 4060. 4140. 4295. 3520. 3425. 3630. 3525. 4220.
 4165. 4325. 4335. 1940. 2740. 2755. 2051. 2075. 1985. 2190. 2815. 2600.
 2720. 1800. 2070. 3365. 3735. 3570. 3535. 3155. 2965. 3430. 3210. 3380.
 3070. 3620. 3410. 3445. 3205. 4080. 2560. 2230. 2515. 2745. 2855. 2405.
 2830. 3140. 2795. 2135. 3245. 2990. 2890. 3265. 3360. 3840. 3725. 3955.
 3830. 4360. 4054. 3605. 1925. 1975. 1915. 2670. 3530. 3900. 3190. 3420.
 2200. 2150. 2020. 2595. 2700. 2556. 2144. 1968. 2120. 2019. 2678. 2870.
 3003. 3381. 2188. 2711. 2434. 2110. 2800. 2085. 2335. 2950. 3250. 1850.
 2145. 1845. 2910. 2420. 2500. 2905. 2290. 2490. 2635. 2620. 2725. 2385.
 1755. 1875. 1760. 2050. 2215. 2380. 2320. 2210. 2350. 2615. 3230. 3160.
 2900. 3415. 3060. 3465. 2605. 2640. 2575. 2525. 2735. 2865. 3035. 1980.
 2025. 1970. 2160. 2205. 2245. 1965. 1995. 3015. 2585. 2835. 2665. 2370.
 2790. 2295. 2625.]
acceleration :
 [12.  11.5 11.  10.5 10.   9.   8.5  8.   9.5 15.  15.5 16.  14.5 20.5
 17.5 12.5 14.  13.5 18.5 19.  13.  19.5 18.  17.  23.5 16.5 21.  16.9
 14.9 17.7 15.3 13.9 12.8 15.4 17.6 22.2 22.1 14.2 17.4 16.2 17.8 12.2
 16.4 13.6 15.7 13.2 21.9 16.7 12.1 14.8 18.6 16.8 13.7 11.1 11.4 18.2
 15.8 15.9 14.1 21.5 14.4 19.4 19.2 17.2 18.7 15.1 13.4 11.2 14.7 16.6
 17.3 15.2 14.3 20.1 24.8 11.3 12.9 18.8 18.1 17.9 21.7 23.7 19.9 21.8
 13.8 12.6 16.1 20.7 18.3 20.4 19.6 17.1 15.6 24.6 11.6]
model_year :
 [70 71 72 73 74 75 76 77 78 79 80 81 82]
origin :
 [1 3 2]
car_name :
 ['chevrolet chevelle malibu' 'buick skylark 320' 'plymouth satellite'
 'amc rebel sst' 'ford torino' 'ford galaxie 500' 'chevrolet impala'
 'plymouth fury iii' 'pontiac catalina' 'amc ambassador dpl'
 'dodge challenger se' "plymouth 'cuda 340" 'chevrolet monte carlo'
 'buick estate wagon (sw)' 'toyota corona mark ii' 'plymouth duster'
 'amc hornet' 'ford maverick' 'datsun pl510'
 'volkswagen 1131 deluxe sedan' 'peugeot 504' 'audi 100 ls' 'saab 99e'
 'bmw 2002' 'amc gremlin' 'ford f250' 'chevy c20' 'dodge d200' 'hi 1200d'
 'chevrolet vega 2300' 'toyota corona' 'ford pinto'
 'plymouth satellite custom' 'ford torino 500' 'amc matador'
 'pontiac catalina brougham' 'dodge monaco (sw)'
 'ford country squire (sw)' 'pontiac safari (sw)'
 'amc hornet sportabout (sw)' 'chevrolet vega (sw)' 'pontiac firebird'
 'ford mustang' 'mercury capri 2000' 'opel 1900' 'peugeot 304' 'fiat 124b'
 'toyota corolla 1200' 'datsun 1200' 'volkswagen model 111'
 'plymouth cricket' 'toyota corona hardtop' 'dodge colt hardtop'
 'volkswagen type 3' 'chevrolet vega' 'ford pinto runabout'
 'amc ambassador sst' 'mercury marquis' 'buick lesabre custom'
 'oldsmobile delta 88 royale' 'chrysler newport royal' 'mazda rx2 coupe'
 'amc matador (sw)' 'chevrolet chevelle concours (sw)'
 'ford gran torino (sw)' 'plymouth satellite custom (sw)'
 'volvo 145e (sw)' 'volkswagen 411 (sw)' 'peugeot 504 (sw)'
 'renault 12 (sw)' 'ford pinto (sw)' 'datsun 510 (sw)'
 'toyouta corona mark ii (sw)' 'dodge colt (sw)'
 'toyota corolla 1600 (sw)' 'buick century 350' 'chevrolet malibu'
 'ford gran torino' 'dodge coronet custom' 'mercury marquis brougham'
 'chevrolet caprice classic' 'ford ltd' 'plymouth fury gran sedan'
 'chrysler new yorker brougham' 'buick electra 225 custom'
 'amc ambassador brougham' 'plymouth valiant' 'chevrolet nova custom'
 'volkswagen super beetle' 'ford country' 'plymouth custom suburb'
 'oldsmobile vista cruiser' 'toyota carina' 'datsun 610' 'maxda rx3'
 'mercury capri v6' 'fiat 124 sport coupe' 'chevrolet monte carlo s'
 'pontiac grand prix' 'fiat 128' 'opel manta' 'audi 100ls' 'volvo 144ea'
 'dodge dart custom' 'saab 99le' 'toyota mark ii' 'oldsmobile omega'
 'chevrolet nova' 'datsun b210' 'chevrolet chevelle malibu classic'
 'plymouth satellite sebring' 'buick century luxus (sw)'
 'dodge coronet custom (sw)' 'audi fox' 'volkswagen dasher' 'datsun 710'
 'dodge colt' 'fiat 124 tc' 'honda civic' 'subaru' 'fiat x1.9'
 'plymouth valiant custom' 'mercury monarch' 'chevrolet bel air'
 'plymouth grand fury' 'buick century' 'chevroelt chevelle malibu'
 'plymouth fury' 'buick skyhawk' 'chevrolet monza 2+2' 'ford mustang ii'
 'toyota corolla' 'pontiac astro' 'volkswagen rabbit' 'amc pacer'
 'volvo 244dl' 'honda civic cvcc' 'fiat 131' 'capri ii' 'renault 12tl'
 'dodge coronet brougham' 'chevrolet chevette' 'chevrolet woody'
 'vw rabbit' 'dodge aspen se' 'ford granada ghia' 'pontiac ventura sj'
 'amc pacer d/l' 'datsun b-210' 'volvo 245' 'plymouth volare premier v8'
 'mercedes-benz 280s' 'cadillac seville' 'chevy c10' 'ford f108'
 'dodge d100' 'honda accord cvcc' 'buick opel isuzu deluxe'
 'renault 5 gtl' 'plymouth arrow gs' 'datsun f-10 hatchback'
 'oldsmobile cutlass supreme' 'dodge monaco brougham'
 'mercury cougar brougham' 'chevrolet concours' 'buick skylark'
 'plymouth volare custom' 'ford granada' 'pontiac grand prix lj'
 'chevrolet monte carlo landau' 'chrysler cordoba' 'ford thunderbird'
 'volkswagen rabbit custom' 'pontiac sunbird coupe'
 'toyota corolla liftback' 'ford mustang ii 2+2' 'dodge colt m/m'
 'subaru dl' 'datsun 810' 'bmw 320i' 'mazda rx-4'
 'volkswagen rabbit custom diesel' 'ford fiesta' 'mazda glc deluxe'
 'datsun b210 gx' 'oldsmobile cutlass salon brougham' 'dodge diplomat'
 'mercury monarch ghia' 'pontiac phoenix lj' 'ford fairmont (auto)'
 'ford fairmont (man)' 'plymouth volare' 'amc concord'
 'buick century special' 'mercury zephyr' 'dodge aspen' 'amc concord d/l'
 'buick regal sport coupe (turbo)' 'ford futura' 'dodge magnum xe'
 'datsun 510' 'dodge omni' 'toyota celica gt liftback' 'plymouth sapporo'
 'oldsmobile starfire sx' 'datsun 200-sx' 'audi 5000' 'volvo 264gl'
 'saab 99gle' 'peugeot 604sl' 'volkswagen scirocco' 'honda accord lx'
 'pontiac lemans v6' 'mercury zephyr 6' 'ford fairmont 4'
 'amc concord dl 6' 'dodge aspen 6' 'ford ltd landau'
 'mercury grand marquis' 'dodge st. regis' 'chevrolet malibu classic (sw)'
 'chrysler lebaron town @ country (sw)' 'vw rabbit custom'
 'maxda glc deluxe' 'dodge colt hatchback custom' 'amc spirit dl'
 'mercedes benz 300d' 'cadillac eldorado' 'plymouth horizon'
 'plymouth horizon tc3' 'datsun 210' 'fiat strada custom'
 'buick skylark limited' 'chevrolet citation' 'oldsmobile omega brougham'
 'pontiac phoenix' 'toyota corolla tercel' 'datsun 310' 'ford fairmont'
 'audi 4000' 'toyota corona liftback' 'mazda 626' 'datsun 510 hatchback'
 'mazda glc' 'vw rabbit c (diesel)' 'vw dasher (diesel)'
 'audi 5000s (diesel)' 'mercedes-benz 240d' 'honda civic 1500 gl'
 'renault lecar deluxe' 'vokswagen rabbit' 'datsun 280-zx' 'mazda rx-7 gs'
 'triumph tr7 coupe' 'ford mustang cobra' 'honda accord'
 'plymouth reliant' 'dodge aries wagon (sw)' 'toyota starlet'
 'plymouth champ' 'honda civic 1300' 'datsun 210 mpg' 'toyota tercel'
 'mazda glc 4' 'plymouth horizon 4' 'ford escort 4w' 'ford escort 2h'
 'volkswagen jetta' 'renault 18i' 'honda prelude' 'datsun 200sx'
 'peugeot 505s turbo diesel' 'volvo diesel' 'toyota cressida'
 'datsun 810 maxima' 'oldsmobile cutlass ls' 'ford granada gl'
 'chrysler lebaron salon' 'chevrolet cavalier' 'chevrolet cavalier wagon'
 'chevrolet cavalier 2-door' 'pontiac j2000 se hatchback' 'dodge aries se'
 'ford fairmont futura' 'amc concord dl' 'volkswagen rabbit l'
 'mazda glc custom l' 'mazda glc custom' 'plymouth horizon miser'
 'mercury lynx l' 'nissan stanza xe' 'honda civic (auto)' 'datsun 310 gx'
 'buick century limited' 'oldsmobile cutlass ciera (diesel)'
 'chrysler lebaron medallion' 'ford granada l' 'toyota celica gt'
 'dodge charger 2.2' 'chevrolet camaro' 'ford mustang gl' 'vw pickup'
 'dodge rampage' 'ford ranger' 'chevy s-10']

In [49]:
adf['horsepower'].unique()

array(['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0',
       '225.0', '190.0', '170.0', '160.0', '95.00', '97.00', '85.00',
       '88.00', '46.00', '87.00', '90.00', '113.0', '200.0', '210.0',
       '193.0', '?', '100.0', '105.0', '175.0', '153.0', '180.0', '110.0',
       '72.00', '86.00', '70.00', '76.00', '65.00', '69.00', '60.00',
       '80.00', '54.00', '208.0', '155.0', '112.0', '92.00', '145.0',
       '137.0', '158.0', '167.0', '94.00', '107.0', '230.0', '49.00',
       '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
       '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
       '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0',
       '108.0', '68.00', '58.00', '149.0', '89.00', '63.00', '48.00',
       '66.00', '139.0', '103.0', '125.0', '133.0', '138.0', '135.0',
       '142.0', '77.00', '62.00', '132.0', '84.00', '64.00', '74.00',
       '116.0', '82.00'], dtype=object)

In [50]:
for i in ['horsepower', 'car_name']: print(i, ':"', (adf[i] == '?').sum())

horsepower :" 6
car_name :" 0

In [51]:
for i in ['horsepower', 'car_name']: print(i, ':"', sum(adf[i] == '?'))

horsepower :" 6
car_name :" 0

In [52]:
adf['horsepower'].to_string().count('?')

6

In [53]:
adf.horsepower.mode()

0    150.0
Name: horsepower, dtype: object

In [54]:
for i in ['horsepower']: adf.replace(['?'], adf.horsepower.mode(), inplace = True)

In [55]:
adf.horsepower.to_string().split("\n")

['0      130.0',
 '1      165.0',
 '2      150.0',
 '3      150.0',
 '4      140.0',
 '5      198.0',
 '6      220.0',
 '7      215.0',
 '8      225.0',
 '9      190.0',
 '10     170.0',
 '11     160.0',
 '12     150.0',
 '13     225.0',
 '14     95.00',
 '15     95.00',
 '16     97.00',
 '17     85.00',
 '18     88.00',
 '19     46.00',
 '20     87.00',
 '21     90.00',
 '22     95.00',
 '23     113.0',
 '24     90.00',
 '25     215.0',
 '26     200.0',
 '27     210.0',
 '28     193.0',
 '29     88.00',
 '30     90.00',
 '31     95.00',
 '32     150.0',
 '33     100.0',
 '34     105.0',
 '35     100.0',
 '36     88.00',
 '37     100.0',
 '38     165.0',
 '39     175.0',
 '40     153.0',
 '41     150.0',
 '42     180.0',
 '43     170.0',
 '44     175.0',
 '45     110.0',
 '46     72.00',
 '47     100.0',
 '48     88.00',
 '49     86.00',
 '50     90.00',
 '51     70.00',
 '52     76.00',
 '53     65.00',
 '54     69.00',
 '55     60.00',
 '56     70.00',
 '57     95.00',
 '58     80.00',
 '59     54.00',
 '60     90.00',
 '61     86.00',
 '62     165.0',
 '63     175.0',
 '64     150.0',
 '65     153.0',
 '66     150.0',
 '67     208.0',
 '68     155.0',
 '69     160.0',
 '70     190.0',
 '71     97.00',
 '72     150.0',
 '73     130.0',
 '74     140.0',
 '75     150.0',
 '76     112.0',
 '77     76.00',
 '78     87.00',
 '79     69.00',
 '80     86.00',
 '81     92.00',
 '82     97.00',
 '83     80.00',
 '84     88.00',
 '85     175.0',
 '86     150.0',
 '87     145.0',
 '88     137.0',
 '89     150.0',
 '90     198.0',
 '91     150.0',
 '92     158.0',
 '93     150.0',
 '94     215.0',
 '95     225.0',
 '96     175.0',
 '97     105.0',
 '98     100.0',
 '99     100.0',
 '100    88.00',
 '101    95.00',
 '102    46.00',
 '103    150.0',
 '104    167.0',
 '105    170.0',
 '106    180.0',
 '107    100.0',
 '108    88.00',
 '109    72.00',
 '110    94.00',
 '111    90.00',
 '112    85.00',
 '113    107.0',
 '114    90.00',
 '115    145.0',
 '116    230.0',
 '117    49.00',
 '118    75.00',
 '119    91.00',
 '120    112.0',
 '121    150.0',
 '122    110.0',
 '123    122.0',
 '124    180.0',
 '125    95.00',
 '126    150.0',
 '127    100.0',
 '128    100.0',
 '129    67.00',
 '130    80.00',
 '131    65.00',
 '132    75.00',
 '133    100.0',
 '134    110.0',
 '135    105.0',
 '136    140.0',
 '137    150.0',
 '138    150.0',
 '139    140.0',
 '140    150.0',
 '141    83.00',
 '142    67.00',
 '143    78.00',
 '144    52.00',
 '145    61.00',
 '146    75.00',
 '147    75.00',
 '148    75.00',
 '149    97.00',
 '150    93.00',
 '151    67.00',
 '152    95.00',
 '153    105.0',
 '154    72.00',
 '155    72.00',
 '156    170.0',
 '157    145.0',
 '158    150.0',
 '159    148.0',
 '160    110.0',
 '161    105.0',
 '162    110.0',
 '163    95.00',
 '164    110.0',
 '165    110.0',
 '166    129.0',
 '167    75.00',
 '168    83.00',
 '169    100.0',
 '170    78.00',
 '171    96.00',
 '172    71.00',
 '173    97.00',
 '174    97.00',
 '175    70.00',
 '176    90.00',
 '177    95.00',
 '178    88.00',
 '179    98.00',
 '180    115.0',
 '181    53.00',
 '182    86.00',
 '183    81.00',
 '184    92.00',
 '185    79.00',
 '186    83.00',
 '187    140.0',
 '188    150.0',
 '189    120.0',
 '190    152.0',
 '191    100.0',
 '192    105.0',
 '193    81.00',
 '194    90.00',
 '195    52.00',
 '196    60.00',
 '197    70.00',
 '198    53.00',
 '199    100.0',
 '200    78.00',
 '201    110.0',
 '202    95.00',
 '203    71.00',
 '204    70.00',
 '205    75.00',
 '206    72.00',
 '207    102.0',
 '208    150.0',
 '209    88.00',
 '210    108.0',
 '211    120.0',
 '212    180.0',
 '213    145.0',
 '214    130.0',
 '215    150.0',
 '216    68.00',
 '217    80.00',
 '218    58.00',
 '219    96.00',
 '220    70.00',
 '221    145.0',
 '222    110.0',
 '223    145.0',
 '224    130.0',
 '225    110.0',
 '226    105.0',
 '227    100.0',
 '228    98.00',
 '229    180.0',
 '230    170.0',
 '231    190.0',
 '232    149.0',
 '233    78.00',
 '234    88.00',
 '235    75.00',
 '236    89.00',
 '237    63.00',
 '238    83.00',
 '239    67.00',
 '240    78.00',
 '241    97.00',
 '242    110.0',
 '243    110.0',
 '244    48.00',
 '245    66.00',
 '246    52.00',
 '247    70.00',
 '248    60.00',
 '249    110.0',
 '250    140.0',
 '251    139.0',
 '252    105.0',
 '253    95.00',
 '254    85.00',
 '255    88.00',
 '256    100.0',
 '257    90.00',
 '258    105.0',
 '259    85.00',
 '260    110.0',
 '261    120.0',
 '262    145.0',
 '263    165.0',
 '264    139.0',
 '265    140.0',
 '266    68.00',
 '267    95.00',
 '268    97.00',
 '269    75.00',
 '270    95.00',
 '271    105.0',
 '272    85.00',
 '273    97.00',
 '274    103.0',
 '275    125.0',
 '276    115.0',
 '277    133.0',
 '278    71.00',
 '279    68.00',
 '280    115.0',
 '281    85.00',
 '282    88.00',
 '283    90.00',
 '284    110.0',
 '285    130.0',
 '286    129.0',
 '287    138.0',
 '288    135.0',
 '289    155.0',
 '290    142.0',
 '291    125.0',
 '292    150.0',
 '293    71.00',
 '294    65.00',
 '295    80.00',
 '296    80.00',
 '297    77.00',
 '298    125.0',
 '299    71.00',
 '300    90.00',
 '301    70.00',
 '302    70.00',
 '303    65.00',
 '304    69.00',
 '305    90.00',
 '306    115.0',
 '307    115.0',
 '308    90.00',
 '309    76.00',
 '310    60.00',
 '311    70.00',
 '312    65.00',
 '313    90.00',
 '314    88.00',
 '315    90.00',
 '316    90.00',
 '317    78.00',
 '318    90.00',
 '319    75.00',
 '320    92.00',
 '321    75.00',
 '322    65.00',
 '323    105.0',
 '324    65.00',
 '325    48.00',
 '326    48.00',
 '327    67.00',
 '328    67.00',
 '329    67.00',
 '330    150.0',
 '331    67.00',
 '332    62.00',
 '333    132.0',
 '334    100.0',
 '335    88.00',
 '336    150.0',
 '337    72.00',
 '338    84.00',
 '339    84.00',
 '340    92.00',
 '341    110.0',
 '342    84.00',
 '343    58.00',
 '344    64.00',
 '345    60.00',
 '346    67.00',
 '347    65.00',
 '348    62.00',
 '349    68.00',
 '350    63.00',
 '351    65.00',
 '352    65.00',
 '353    74.00',
 '354    150.0',
 '355    75.00',
 '356    75.00',
 '357    100.0',
 '358    74.00',
 '359    80.00',
 '360    76.00',
 '361    116.0',
 '362    120.0',
 '363    110.0',
 '364    105.0',
 '365    88.00',
 '366    85.00',
 '367    88.00',
 '368    88.00',
 '369    88.00',
 '370    85.00',
 '371    84.00',
 '372    90.00',
 '373    92.00',
 '374    150.0',
 '375    74.00',
 '376    68.00',
 '377    68.00',
 '378    63.00',
 '379    70.00',
 '380    88.00',
 '381    75.00',
 '382    70.00',
 '383    67.00',
 '384    67.00',
 '385    67.00',
 '386    110.0',
 '387    85.00',
 '388    92.00',
 '389    112.0',
 '390    96.00',
 '391    84.00',
 '392    90.00',
 '393    86.00',
 '394    52.00',
 '395    84.00',
 '396    79.00',
 '397    82.00']

In [56]:
adf['horsepower'].to_string().count('?')

0

In [57]:
adf.horsepower = adf.horsepower.astype(float)
adf.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower      float64
weight          float64
acceleration    float64
model_year        int64
origin            int64
car_name         object
dtype: object

# Titanic Data Analysis

In [58]:
tdf = pd.read_csv(r".\Datasets\titanic-dataset.csv")
tdf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [59]:
tdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [60]:
tdf.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [61]:
tdf.Age.mean()

29.69911764705882

In [62]:
tdf.Age.fillna(tdf.Age.mean(), inplace = True)

In [63]:
tdf.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [64]:
tdf.Embarked.unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [65]:
tdf.Embarked.mode()

0    S
Name: Embarked, dtype: object

In [66]:
for i in ['Embarked']: tdf.Embarked.replace([np.NaN], tdf.Embarked.mode(), inplace = True)

In [67]:
tdf.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [68]:
tdf.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64', 'E24', 'C90', 'C45', 'E8', 'B101', 'D45', 'C46', 'D30',
       'E121', 'D11', 'E77', 'F38', 'B3', 'D6', 'B82 B84', 'D17', 'A36',
       'B102', 'B69', 'E49', 'C47', 'D28', 'E17', 'A24', 'C50', 'B42',
       'C148'], dtype=object)

In [69]:
tdf.Cabin.mode()

0        B96 B98
1    C23 C25 C27
2             G6
Name: Cabin, dtype: object

In [70]:
tdf.describe(include = 'O')

                           Name   Sex  Ticket    Cabin Embarked
count                       891   891     891      204      891
unique                      891     2     681      147        3
top     Braund, Mr. Owen Harris  male  347082  B96 B98        S
freq                          1   577       7        4      646

In [71]:
tdf.describe(include = 'O')['Cabin'][2]

'B96 B98'

In [72]:
for i in ['Cabin']: tdf.Cabin.replace([np.NaN], tdf.describe(include = 'O')[i][2], inplace = True)

In [73]:
tdf.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64